#include <stdio.h>
#include <stdlib.h>
#include <gmp.h>

/* 
 * Saha-Sinha formula for computing pi using GMP library.
 * This code generated by Grok AI.
 * This implementation uses the Pochhammer symbol and factorials.
 * The precision can be adjusted by changing the `prec` variable.
 * 
 * Compile with: gcc -o pi_cal_saha_gmp pi_cal_saha_gmp.c -lgmp
 */


/* Initialize GMP variables with given precision (in bits) */
void init_mp(mpf_t var, unsigned long prec) {
    mpf_init2(var, prec);
}

/* Compute factorial: n! */
void factorial(mpf_t result, int n) {
    mpf_set_ui(result, 1);
    for (int i = 1; i <= n; ++i) {
        mpf_mul_ui(result, result, i);
    }
}

/* Compute Pochhammer symbol: (x)_n = x(x+1)...(x+n-1) */
void pochhammer(mpf_t result, mpf_t x, int n) {
    mpf_set_ui(result, 1);
    mpf_t temp;
    init_mp(temp, mpf_get_prec(result));
    for (int i = 0; i < n; ++i) {
        mpf_set(temp, x);
        mpf_add_ui(temp, temp, i);
        mpf_mul(result, result, temp);
    }
    mpf_clear(temp);
}

/* Saha-Sinha formula for pi */
void compute_pi(mpf_t pi, mpf_t lambda, int terms, unsigned long prec) {
    mpf_t sum, term1, term2, temp, n_plus_lambda, two_n_plus_one, factorial_n;
    init_mp(sum, prec);
    init_mp(term1, prec);
    init_mp(term2, prec);
    init_mp(temp, prec);
    init_mp(n_plus_lambda, prec);
    init_mp(two_n_plus_one, prec);
    init_mp(factorial_n, prec);

    mpf_set_ui(sum, 0);

    for (int n = 1; n <= terms; ++n) {
        /* term1 = 1/(n+lambda) - 4/(2n+1) */
        mpf_set_ui(n_plus_lambda, n);
        mpf_add(n_plus_lambda, n_plus_lambda, lambda);
        mpf_ui_div(term1, 1, n_plus_lambda); /* 1/(n+lambda) */

        mpf_set_ui(two_n_plus_one, 2 * n + 1);
        mpf_ui_div(temp, 4, two_n_plus_one); /* 4/(2n+1) */
        mpf_sub(term1, term1, temp);

        /* term2 = ((2n+1)^2 / (4(n+lambda)) - n)_{n-1} */
        mpf_set_ui(temp, 2 * n + 1);
        mpf_mul(temp, temp, temp); /* (2n+1)^2 */
        mpf_set_ui(n_plus_lambda, n);
        mpf_add(n_plus_lambda, n_plus_lambda, lambda);
        mpf_mul_ui(n_plus_lambda, n_plus_lambda, 4); /* 4(n+lambda) */
        mpf_div(temp, temp, n_plus_lambda); /* (2n+1)^2 / (4(n+lambda)) */
        mpf_sub_ui(temp, temp, n); /* - n */
        pochhammer(term2, temp, n - 1);

        /* Combine: term1 * term2 / n! */
        factorial(factorial_n, n);
        mpf_mul(temp, term1, term2);
        mpf_div(temp, temp, factorial_n);
        mpf_add(sum, sum, temp);
    }

    /* pi = 4 + sum */
    mpf_set_ui(pi, 4);
    mpf_add(pi, pi, sum);

    mpf_clear(sum);
    mpf_clear(term1);
    mpf_clear(term2);
    mpf_clear(temp);
    mpf_clear(n_plus_lambda);
    mpf_clear(two_n_plus_one);
    mpf_clear(factorial_n);
}

int main(int argc, char *argv[]) {
    /* Set precision (in bits, ~50 digits) */
    unsigned long prec = 160;
    mpf_t lambda, pi;
    init_mp(lambda, prec);
    init_mp(pi, prec);

    /* Set lambda and terms */
    mpf_set_d(lambda, 3.0); /* Faster convergence with lambda = 3 */
    int terms = 30;         /* ~10 decimal places */

    if (argc > 1) {
        mpf_set_d(lambda, atof(argv[1]));
    }
    if (argc > 2) {
        terms = atoi(argv[2]);
    }

    /* Compute pi */
    compute_pi(pi, lambda, terms, prec);

    /* Print result */
    printf("Computed pi (lambda=%.2f, terms=%d): \n", mpf_get_d(lambda), terms);
    gmp_printf("%.50Ff\n", pi);
    printf("Reference pi: \n3.14159265358979323846264338327950288419716939937510\n");

    mpf_clear(lambda);
    mpf_clear(pi);
    return 0;
}